language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.m2/repository
    
before_script:
  - cd ohouse

script: "mvn clean package"

before_deploy:
  - zip -r webservice-ohouse *
  - mkdir -p deploy
  - mv webservice-ohouse.zip deploy/webservice-ohouse.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ohouse-springboot-build
    region: ap-northeast-2
    acl: private
    local_dir: deploy

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ohouse-springboot-build
    key: webservice-ohouse.zip
    bundle_type: zip
    application: webservice-ohouse
    deployment_group: webservice-ohouse-group
    region: ap-northeast-2

notifications:
  email:
    recipients:
      - jn7277@hotmail.com
    on_success: always
    on_failure: always
