language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.m2

script: "mvn clean install"

before_deploy:
  - zip -r webservice-ohouse *
  - mkdir -p deploy
  - mv webservice-ohouse.zip deploy/webservice-ohouse.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: ohouse-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy

notifications:
  email:
    recipients:
      - jn7277@hotmail.com
    on_success: always
    on_failure: always
