language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - $HOME/.m2

script: "./mvnw clean package"

notifications:
  email:
    recipients:
      - jn7277@hotmail.com
    on_success: always
    on_failure: always
